branches:
  only:
    - main
language: node_js
node_js:
  - lts/*
git:
  depth: 30
install:
  - yarn --frozen-lockfile
  - yarn test
before_script:
  - chmod +x build.sh  notify.sh
script:
  - ./build.sh
after_script:
  - ./notify.sh
cache: yarn
deploy:
  - provider: npm
    email: yuwangifeng@163.com # use your own email
    api_key: $NPM_TOKEN
    skip-cleanup: true
    on:
      branch: main
