branches:
  only:
    - main
language: node_js
node_js:
  - lts/*
git:
  depth: 30
install:
  - yarn --frozen-lockfile
  - yarn test
before_script:
  - chmod +x gradlew
script:
  - ./build.sh
after_script:
  - ./notify.sh
cache: yarn
deploy:
  - provider: pages # you may delete this provider if you don't need deployment of github pages
    local-dir: docs # https://docs.travis-ci.com/user/deployment/packagecloud/#specify-package-folder
    github-token: 46d2211730a0fceff92cd842a60f651c458d1c3d
    skip-cleanup: true
    keep-history: true
    on:
      branch: main
  - provider: npm
    email: yuwangifeng@163.com # use your own email
    api_key: elX5TojNm-s9zn80MqjN2w
    skip-cleanup: true
    on:
      branch: main
